default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 
  host: localhost
  collation: utf8mb4_general_ci

development:
  <<: *default
  database: photography_development

test:
  <<: *default
  database: photography_test

production:
  <<: *default
  database: photography_production

