# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f45d193ba80b4902c0e5b0e5b3f6213e90aebc95ee7f3e57bfdf3a99dfb539e71cfadc96ce0006fa8cb8d91890c3a105d9b4d4bccde3391d5ab8c44f9b5e24c2

test:
  secret_key_base: 0f7727e6b49da96693801e20d18fd3a6b0fd55a2ad5dbab9a2c647bd77cb815c12bbf1765845fd174516a0d681c1a807c7095dda91d2bfce9affa7cbe019f4fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
